CREATE TYPE sort_things_options AS ENUM (
  'Title',
  'Newest-upload',
  'Oldest-upload',
  'Recent-update'
);

-- title is alpha-numeric ascending
-- newest-upload is upload date descending
-- oldest-upload is upload date ascending
-- recent-update is last update or comment date descending (first is most recent)

CREATE TYPE filter_things_options AS ENUM (
  'None',
  'Concerns-me-only',
  'Needs-vote-only'
);

-- concerns me is any thing with a vote that mentions me (may include votes for others as well)
-- needs-vote is any thing that current user has not voted on (combined with oldest-upload, focuses attention on what a person needs to do)

CREATE TABLE users (
  id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  first_name         TEXT NOT NULL,
  last_name          TEXT,
  email              TEXT NOT NULL UNIQUE,
  password           TEXT NOT NULL,
  group_id           INTEGER REFERENCES groups(id) ON DELETE SET NULL,

  sort_preferences   sort_things_options,
  filter_preferences filter_things_options,
  
  date_created TIMESTAMP NOT NULL DEFAULT now(),
  date_updated TIMESTAMP NOT NULL DEFAULT now()
);