CREATE TABLE things (
    id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,

    title               TEXT NOT NULL,
    description         TEXT,
    pieces              INTEGER DEFAULT 1,

    uploaded_by_user_id INTEGER REFERENCES users(id) ON DELETE SET NULL,
    group_id            INTEGER REFERENCES groups(id) ON DELETE SET NULL,

    hero_pic_id         INTEGER REFERENCES pics(id) ON DELETE SET NULL,
    thumb_pic_id        INTEGER REFERENCES pics(id) ON DELETE SET NULL,
    
    date_created        TIMESTAMP DEFAULT now() NOT NULL,
    date_updated        TIMESTAMP DEFAULT now() NOT NULL

);
